//! إنشاء src/stark/field.rs
//! Auto-generated by Forge Agent

pub struct FieldElement { pub value: u64, pub modulus: u64 }

impl FieldElement {
    pub fn new(value: u64, modulus: u64) -> Self { Self { value: value % modulus, modulus } }
    pub fn add(&self, other: &Self) -> Self { Self::new(self.value + other.value, self.modulus) }
    pub fn mul(&self, other: &Self) -> Self { Self::new(self.value * other.value, self.modulus) }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_new() {
        let a = FieldElement::new(3, 17);
        let b = FieldElement::new(5, 17);
        assert_eq!(a.add(&b).value, 8);
    }
}
