//! إنشاء src/stark/zk_verifier.rs
//! Auto-generated by Forge Autonomous Agent
//! Module: src::stark::zk_verifier

/// zk-STARK Verifier - fast verification in milliseconds
use crate::stark::zk_prover::ZKProof;

pub struct ZKVerifier;

impl ZKVerifier {
    pub fn verify(proof: &ZKProof) -> bool {
        !proof.proof_data.is_empty() && !proof.public_inputs.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::stark::zk_prover::ZKProof;
    #[test]
    fn test_zk_verifier() {
        let proof = ZKProof { proof_data: vec![1u8; 64], public_inputs: vec![1, 2] };
        assert!(ZKVerifier::verify(&proof));
    }
}
